services:
    crafataravatar.crafatarphpbb.minecraftcrafatar:
        class: crafataravatar\crafatarphpbb\avatar\driver\minecraftcrafatar
        arguments:
            - '@config'
            - '@upload_imagesize'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@path_helper'
            - '@cache.driver'
        calls:
            - [set_name, [crafataravatar.crafatarphpbb.minecraftcrafatar]]
        tags:
            - { name: avatar.driver }

    crafataravatar.crafatarphpbb.listener:
        class: crafataravatar\crafatarphpbb\event\listener
        arguments:
            - '@user'
            - '@config'
            - '@request'
            - '@template'
        tags:
            - { name: event.listener }
